[project]
name = "neural-network"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "matplotlib>=3.10.8",
    "mplcursors>=0.7",
    "numpy>=2.4.2",
    "torchvision>=0.25.0",
]
